# Generated by Django 3.0.5 on 2021-03-29 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
    ]
