# Generated by Django 3.0.5 on 2021-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_auto_20210329_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('psw', models.CharField(max_length=150)),
                ('psw_repeat', models.CharField(max_length=150)),
            ],
        ),
    ]
