# Generated by Django 3.0.5 on 2021-04-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='signup',
            name='psw',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='signup',
            name='psw_repeat',
            field=models.CharField(default='', max_length=150),
        ),
    ]
