# Generated by Django 3.0.5 on 2021-04-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='fname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='signup',
            name='lname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
